version: '3'

services:
  simulation:
    image: maven:alpine
    command: java -jar /app/simulation-service-1.0.0.jar
    volumes:
      - ./target:/app/
    ports:
      - 8300:8080
    environment:
      DATABASE_URL: jdbc:mysql://192.168.178.24:3300/projectdb
      DATABASE_USER: mysql
      DATABASE_PASS: mysql
    env_file:
      - ./secrets.env