version: '3.1'

services:
  simulation:
    image: yoksar/simulation-service
    environment:
      GOOGLE_SECRET_LOCATION: /run/secrets/google-api-key
      LOAD_FROM_FILE: 'true'
    secrets:
      - google-api-key
    ports:
      - 8300:8080
    restart: unless-stopped

secrets:
  google-api-key:
    external: true 