kumuluzee:
  name: simulation-service
  datasources:
    - jndi-name: jdbc/simulation
      connection-url: '${DATABASE_URL}'
      username: '${DATABASE_USER}'
      password: '${DATABASE_PASS}'
      pool:
        max-size: 20


config:
  google:
    directionsApi:
      key: '${GOOGLE_API_KEY}'