kumuluzee:
  name: simulation-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080

config:
  google:
    directionsApi:
      key: '${GOOGLE_API_KEY}'